### ISSUE TITLE
.cfg file requirements / naming requirements

### ISSUE THREAD

**Issue by FransBouma** [crosire/reshade-shaders#1]
Hey,

I'd like to merge my small effect lib OtisFX (https://github.com/FransBouma/OtisFX) with the general framework, but I have two questions:

- the mediator requires to have the .cfg files to have a given format. I can look at the cfg files and look for a common theme, that's quite easy, but I do recall at some spots spaces aren't allowed or e.g. for float value ranges, they have to be specified with a scale ([0.0:1.0] instead of [0.1]). Is that (still) the case? 

- I named the #defines rather arbitrary and ditto for the method names, using various prefixes with allcaps. I see inconsistency among the shaders in the framework for naming rules, but just to be safe: is there a naming guideline to follow so my effects follow the rules at least? 

TIA.

ps: I'd like to keep them in a separate 'suite', if that's OK. If that's not possible, I'll keep them separate.

**Comment by crosire** [comment]
The whole 'suite' thing is likely to change soon: I proposed to sort shaders by author names instead to the team, which could help to bring some order in the whole naming mess.

As for variable naming rules: We don't really have any right now (yet) and everybody seems to do it differently, hence the inconsistency. I hope there will be a general refactoring some time soon in the future (together with the transition from suites to a simpler organization form), in which a general naming scheme could be implemented. ReShade FX supports namespaces (a concept well known from languages like C++), so those may help a big deal here (although they of course don't apply to preprocessor defines).

The question about the configuration file format I cannot answer, @Ganossa?

**Comment by Ganossa** [comment]
Hey Ortis,

As Crosire already said, your suite will be your development environment and called "Ortis" (if that is your nickname. It will also be changed for all other suites, once everyone agrees on it.

We had a naming guideline but did not follow through with it. Mainly because we are still in discussion, not everyone got warm yet with the framework and I will not just rename everyone's work. There is also a minor bug yet in the namespaces which would hold us back. We are working on a new guideline for the upcoming release that everyone can agree with (for variables most likely based on Marty's current naming conventions). Most of what will change can change right before a release or when we decided, so do not worry about it yet.

Single spaces between each element in a .cfg file are currently the rule. 
A vector can currently only be a float and should have no space (correct is e.g. float4(0.1,0.2,0.3,0.4)). All their range will be the same and is defined as for single variables.
Ranges are defined as [1.0:2.0]. Note that you have to be consistent with the fraction size (also for the default value!!), since it defines the steps of a scroll bar in the mediator ([0:10] has 11 steps, [0.0:10.0] has 10 times as much).
If you have something which is not covered by range, simply put [undef]. It will create a text field in the mediator instead.

Any more questions? :)

PS: The mediator will be renamed to ReShadeAssistant with the next update.

**Comment by FransBouma** [comment]
Hey! 

It's 'Otis' (without the 'r' ;)) yeah that's my nickname since my old demoscene days. :)

About naming: I saw Marty uses hungarian for some variables/defines... not sure if that's a good idea to choose as a standard, it was all the rage in the '90-ies but nowadays it's not really that common. I'll stick with the names I have for now (I've tried to make things unique and descriptive). 

Thanks for the details on the config file format, I'll fix up the cfg file I have before the pull request. 

I hope to have time to send the PR in the coming days!

**Comment by martymcmodding** [comment]
I use Hungarian? Considering that I don't speak  speak this language, where did I do this?
Plus my naming "convention" is mostly 
iSomeVariable for an integer, fSomeVariable for a float and so on. For a specific shader, let's say my ADOF, I have fADOFSomeVariable. Internally, I have random names for the variable but mostly lowercase and some fixed names I use for all shaders out of habit, such as scenedepth, discRadius or such.

**Comment by FransBouma** [comment]
https://en.wikipedia.org/wiki/Hungarian_notation :)

**Comment by crosire** [comment]
Agreed, hungarian notation is somewhat outdated. Especially nowadays with IDEs, that show the respective variable type when hovering over it.

**Comment by martymcmodding** [comment]
Never heard of that, lol
Why is it called Hungarian then...confusing. 
We have no real IDE, that's the thing though. And from all the disadvantages Wikipedia lists none are really applying here. Plus it's used for config values only. As long as I don't need to change my behaviour in the code itself, everything is fine to me.

**Comment by FransBouma** [comment]
It's called hungarian because of the inventor of it, Simonyi, is Hungarian. Anyway, it's one of these things which indeed work OK outside an IDE. I've used it for many years and it works great, till a var changes a type or something, but with shaders it's not that big of a deal.

**Comment by FransBouma** [comment]
Solved
