### ISSUE TITLE
Effects ordering: AA should be applied before noise effects to avoid pixel flickering

### ISSUE THREAD

**Issue by aufkrawall** [crosire/reshade-shaders#14]
By default, e.g. Deband is applied before SMAA/FXAA, but the noise of Deband makes the AA (probably mainly SMAA) to produce flickering pixels.

**Comment by aufkrawall** [comment]
Btw: Is it to be expected that the very current shaders aren't functioning?
Seems like ReShade doesn't find any shaderpack.

**Comment by JPulowski** [comment]
The latest available binaries are currently not compatible with the current framework structure due to changes in preprocessor instructions. It should be kept in mind that the files on the repository are "nightly" or "beta" versions in a way, which means they might not always work with the latest available binaries. I cannot give an exact ETA but the next release which contains 2.0 binaries should be soon.

The reason why I put Deband before SMAA in the pipeline, because in my experiments Deband shader produced the most optimal results when it is applied before everything else. Can you elaborate what do you mean by "flickering pixels"? It would be even better if you could provide a screenshot. If it is caused because of random dithering, I might try another dithering technique such as ordered dithering etc.

**Comment by aufkrawall** [comment]
It can oly be seen in videos and they probably need a high bitrate.
It's not a specific issue with noise effects of ReShade. The same will happen when you inject SMAA into a game that has e.g. some kind of filmgrain. When you look closely at certain edges, you see that there are flickering areas which stop flickering when you turn off either SMAA or grain effect. The AA detection of SMAA gets confused by the grain.
With ReShade effects, this can be avoided by effects ordering.
I suggest that AA gets its own entry in the pipeline.cfg at the very top. I assume that the effect of mere AA is very low on the effect of Deband filter (at least if considered subpixel amount isn't insanely high with FXAA).

**Comment by crosire** [comment]
No longer relevant due to restructure in ReShade 3.0 (there is no default effect order).
