### ISSUE TITLE
Make use of gpuopen effect ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [crosire/reshade-shaders#19]
Recently AMD has opensourced it's effects, maybe you can do this effect on a general way for work on all games ? 
Sorry for my bad english 
https://github.com/GPUOpen-Effects

**Comment by crosire** [comment]
These are advanced rendering effects and not used in post-processing.

**Comment by LifeIsStrange** [comment]
I'm sorry but the ambiant occlusion is a post processing effect from what Wikipedia say. 
https://github.com/GPUOpen-Effects/AOFX
You are right for the others effects but watch AOFX please

**Comment by martymcmodding** [comment]
AOFX (HDAO) uses deinterleaving/reinterleaving to improve cache efficiency. As this can hardly be done on ReShade, a highly modified port of the HDAO shader would be needed. The valley detection of HDAO is just another approach on estimating the occlusion based on sample points. From my tests, my own AO is superior to HDAO, at least on ReShade. I can however port the HDAO that was used in OBGE v3, this is an older version but code-wise largely same. But as I said already, the occlusion estimation of my AO is superior. And HDAO is only occlusion, my AO can handle indirect lighting, like SSDO.

**Comment by Swartz27** [comment]
@martymcmodding Which AO method is yours? The SSGI? I'm just curious.

**Comment by LifeIsStrange** [comment]
Ok I understund thanks :)

**Comment by martymcmodding** [comment]
It's not out yet.

**Comment by LifeIsStrange** [comment]
@martymcmodding 
When this will be ready and if as you said "From my tests, my own AO is superior to HDAO"  It is superior to the AMD solution, could you suggest to AMD via github to use your AO solution in gpuopen, if you do this a lot of future Games and AAA will use your effect on PC and even on consoles ! This should be awesome :) 
Also AMD could improve your AO solution. 
Sorry for my bad english.

**Comment by Swartz27** [comment]
@LifeIsStrange I kinda doubt a large company is going to accept a shader they didn't design themselves as it would mean paying him, which they're not going to want to do (and he should be paid, not give it for free to some company if it truly is better). 

Besdies, in some ways GPU Open is sorta like Nvidia Gameworks: not as restricted, and can be used on any GPU, but they still conceal certain aspects of how things work within a dll. They don't just post raw shaders anymore it seems.

**Comment by LifeIsStrange** [comment]
"as it would mean paying him, which they're not going to want to do"
Why ? They already pay devs to work on their AO, so they can pay him if the result is better. 

" and he should be paid, not give it for free to some company if it truly is better"
I disagree, it's free software, AMD give us free software via gpuopen, we should also give free software to gpuopen 

But if he want to be paid I think it's not a problem and you (martymcmodding) have nothing to waste to ask to AMD if they want or no.

**Comment by LifeIsStrange** [comment]
Also since nvidia has launched hbao+ and now vxao, AMD really need a counterpart. 
And the pc and console gaming industry need an opensource, optimised on all hardware counterpart. Because all this gameworks stuff work very bad on AMD and Intel. 

@martymcmodding you can be the man which provide for all this so needed counterpart :)

**Comment by martymcmodding** [comment]
MXAO is really fast, compared to other solutions. If I manage to port HBAO+ to ReShade, I can make a definite comparison - also about scalability, MXAO is unbeaten from all my tests at high range AO because for most algorithms, the cache efficiency goes to hell if you raise the radius too much. That's also part of what makes Boris Vorontsov's SSAO so good, you can use screen size big radii and the fps barely suffer from such a stunt, which makes other algorithms cripple at 10 fps. Try it out yourself: use any AO in the framework and crank the values up beyond the recommended ranges, you'll see that their fps impact will be horrible.

**Comment by Swartz27** [comment]
Hey Marty, I attempted to email you and it turned out it was another person working on Reshade, guess I got confused :P Anyway, since your email isn't available I'm just going to paste my email here:

> Hello, I hope you don't mind that I tracked down your email through your github profile, I just wanted to chat with you.
> 
> I can see that you're very skilled with graphical effects/HLSL.
> 
> Currently I'm working on a game "mod" for the game "Stalker: Call of Pripyat" called Radium.
> 
> Anyway, from what you've been saying about your upcoming AO method, it sounds exciting.
> I was wondering about three possibilities:
> 
> 1) You allow me to port this upcoming effect to my mod (I have the source code and disabled the shaders cache so I can edit the DX11 shaders, I can add new samplers, etc.). The only problem is is that I'm still a beginner with HLSL, and before, when I didn't realize I'm not supposed to without permission, I attempted to port a few Reshade shaders, including your SAO, but it didn't turn into anything I could see in the game, so I obviously have more to learn in that regard. However, if you allowed me to use your upcoming effect, assuming it's as good as you say it is, I would be thrilled :)
> 
> 2) I can (in the not so distant future) pay you to port the shader into Call of Pripyat for me. I don't want to promise payment, as I am awaiting disability for which I would receive a great deal of backpay for the time I've waited, but there is always the possibility they'll deny my claim and I'll have to apply again. Anyway, I can basically show you how the shaders and various samplers are set up in Call of Pripyat. It's pretty straightforward, especially in regards to AO.
> 
> 3) This is unlikely, but if you were interested in joining a mod team as a graphics programmer, I could certainly use you. I'm scraping by so far, but I always welcome more people. Or, alternatively, if you know of any graphics programmers that might be interested.
> 
> P.S. I noticed you mentioned something about porting HBAO+ on Github. I'm a registered Gameworks developer, and although they keep it closed-source (they provide you with the needed header, library, and dll), from how they describe it internaly, it simply sounds like a hybrid of HBAO and SAO. Seems like "Horizon Based Scalable Ambient Obscurance" might have been a better name ;)

**Comment by martymcmodding** [comment]
1) No problem with that. However I don't have the game and can't test anything, hence I cannot assist you in any way. My time is too much limited for such things even though I'd really like to. SAO is a bitch to implement, most likely because the implementation in ReShade is a bit dirty so you're probably better off taking the source from the SAO devs themselves instead of my adaptation. If I was to port it again, I'd do it better. Maybe I even will because adding my AO requires quite some restructuring in the AO "pipeline", that's why I didn't do it yet. I am not 100% sure if you can implement it rightaway into a different system because it relies on multi render targets rendering - you could set up a different pass for each of those textures but the performance would suffer. But from the handling, it's a lot better than SAO as my beta testers told me that it works reliably on almost every game, even those where ReShade grabs faulty depth buffers and no other depth depending effects work properly.

2) You can pay or not pay me. I'm not about the money so if you want to reward my for this, I'm okay with any sum (including 0).

3) I'd really like to but eh, free time. If this was a year ago, I would be able to spend 8 hours per day on this...but on the other hand I would be less experienced and not useful anyways :P 

About the HBAO+, I'm mainly interested how they distribute their samples as the quality of an AO shader is highly dependant on that. If you use a shitty random generator or a bad distribution formula, samples clump around certain values and so the effective sample count is much lower. That's one of the things that makes SAO so hard to tweak because it needs this spiral array where they adjust the rotation angle of their sample spiral to avoid samples from lining up. From what I have seen in the HBAO+ documentation, it looks really smooth even with no blurring.
